name: football-edge
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - xgboost
  - statsmodels
  - matplotlib
  - pip:
      - optuna
      - mlflow
      - streamlit
      - pyyaml
      - joblib
      - shap
